# Generated by Django 4.0.2 on 2023-02-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.IntegerField(default=None)),
                ('csv_file', models.FileField(default=None, max_length=10000000000000, null=True, upload_to='files/')),
            ],
        ),
    ]
