# Generated by Django 4.0.2 on 2023-02-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='csv_file',
            field=models.FileField(default=None, upload_to='media/'),
        ),
    ]
