# Generated by Django 4.0.2 on 2023-02-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_index_csv_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='csv_file',
        ),
        migrations.AddField(
            model_name='index',
            name='csvfile',
            field=models.FileField(default=False, upload_to='files/'),
        ),
    ]
